server:
  port: 8080
spring:
  application:
    #应用名称 , 可选
    name: kdtx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huike?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 7
    #password: 123456
    #database: 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper配置文件
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: org.itcast.entity



logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info